---
- name: Create app directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - "{{ app_dir }}"
    - "{{ app_dir }}/logs"
    - "{{ app_dir }}/config"
    - "{{ app_dir }}/vault"
    - "{{ app_dir }}/vault/scripts"

- name: Create systemd service file
  template:
    src: currency-bot.service.j2
    dest: /etc/systemd/system/currency-bot.service
    mode: '0644'
  notify: reload systemd

- name: Enable app service
  systemd:
    name: currency-bot
    enabled: yes
    daemon_reload: yes