pipeline {
    agent any

    environment {
        TF_DIR = 'lab6/terraform'
        ANSIBLE_DIR = 'lab6/ansible'
        GEN_INV_SCRIPT = "${ANSIBLE_DIR}/generate_inventory.sh"
        INVENTORY_FILE = "${ANSIBLE_DIR}/inventory.yml"
    }

    stages {
        stage('Checkout') {
            steps {
                echo '📥 Checking out...'
                checkout scm
                sh "chmod +x ${GEN_INV_SCRIPT}"
            }
        }

        stage('Terraform Apply') {
            steps {
                echo '☁️ Creating infrastructure...'
                dir("${TF_DIR}") {
                    sh 'terraform init -input=false'
                    withCredentials([string(credentialsId: 'yc-token', variable: 'YC_TOKEN')]) {
                        sh """
                            export YC_TOKEN=\${YC_TOKEN}
                            terraform apply -auto-approve -input=false
                        """
                    }
                }
            }
        }

        stage('Generate Inventory') {
            steps {
                echo '📝 Generating inventory...'
                sh """
                    ${GEN_INV_SCRIPT}
                    cat ${INVENTORY_FILE}
                """
            }
        }

        stage('Ansible Playbook') {
            steps {
                echo '🏗 Running playbook...'
                dir("${ANSIBLE_DIR}") {
                    withCredentials([string(credentialsId: 'bot-token', variable: 'BOT_TOKEN')]) {
                        sh """
                            ansible-playbook -i inventory.yml playbook.yml \\
                                --extra-vars "bot_token=\${BOT_TOKEN}" -v
                        """
                    }
                }
            }
        }

        stage('Ansible Deploy') {
            steps {
                echo '🚀 Deploying app...'
                dir("${ANSIBLE_DIR}") {
                    sh "ansible-playbook -i inventory.yml deploy.yml -v"
                }
            }
        }

        stage('Verify') {
            steps {
                echo '✅ Verifying...'
                script {
                    def vmIP = sh(
                        script: "grep ansible_host ${INVENTORY_FILE} | awk '{print \$2}'",
                        returnStdout: true
                    ).trim()
                    echo "🎯 VM IP: ${vmIP}"

                    // Используем sshagent для подключения
                    sshagent(credentials: ['vm-ssh-key']) {
                        sh """
                            ssh -o StrictHostKeyChecking=no ubuntu@${vmIP} "sudo systemctl is-active currency-bot"
                        """
                    }
                }
            }
        }
    }

    post {
        success { echo '🎉 Success!' }
        failure { echo '❌ Failed!' }
        always { cleanWs() }
    }
}