apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
data:
  # Vault
  SPRING_CLOUD_VAULT_URI: "http://vault:8200"
  SPRING_CLOUD_VAULT_PORT: "8200"

  # MongoDB
  MONGODB_HOST: "mongodb" # DNS-имя сервиса
  MONGODB_PORT: "27017"

  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  # Приложение
  SERVER_PORT: "8081"
  SPRING_APPLICATION_NAME: "currency-converter-bot"
  SPRING_CLOUD_VAULT_FAIL_FAST: "true"