apiVersion: v1
kind: Service
metadata:
  name: currency-bot-service
spec:
  type: NodePort
  selector:
    app: currency-bot
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081  # Доступ из браузера: http://localhost:30081