apiVersion: v1
kind: Service
metadata:
  name: currency-bot-service
spec:
  type: NodePort # Тип сервиса: доступ через порт на ноде
  selector:
    app: currency-bot # Направляет трафик на поды с этим лейблом
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081  # Доступ из браузера: http://localhost:30081