apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.16.0
          imagePullPolicy: IfNotPresent
          command: [ "vault" ]
          args: ["server", "-dev", "-dev-root-token-id=test-token", "-dev-listen-address=0.0.0.0:8200"]
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "test-token"
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8200"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 10  # Чуть больше времени на старт
            periodSeconds: 5
          # Добавляем volume для persistence (как в Ansible)
          volumeMounts:
            - name: vault-data
              mountPath: /vault/file
      volumes:
        - name: vault-data
          emptyDir: {}  # Временное хранилище
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200